rvm:
  - 1.9.3
  - 2.0.0 
  - 2.1.0
  - rbx-19mode
  - jruby-19mode

gemfile:
  - gemfiles/Gemfile.rails-3.2
  - gemfiles/Gemfile.rails-4.0

env:
  - ADAPTER=active_record
  - ADAPTER=mongoid

services: mongodb

before_script: rails --version
