rvm:
    - 1.8.7
    - 1.9.2
    - 1.9.3
    - ruby-head
    - rbx
    - jruby
    - ree

env:
    - ADAPTER=active_record
    - ADAPTER=mongoid

before_install:
  - gem update --system
  - gem --version
