language: ruby

before_install:
  - gem update --system
  - gem install bundler
  - gem --version

script: bundle exec rake

after_success:
  - bundle exec codeclimate-test-reporter

rvm:
  - 2.7.0
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - 2.3.8

gemfile:
  - gemfiles/activerecord_4.gemfile
  - gemfiles/activerecord_5.gemfile
  - gemfiles/activerecord_6.gemfile
  - gemfiles/mongoid_5.gemfile
  - gemfiles/mongoid_6.gemfile
  - gemfiles/mongoid_7.gemfile

env:
  - ADAPTER=active_record
  - ADAPTER=mongoid

matrix:
  exclude:
    - gemfile: gemfiles/activerecord_4.gemfile
      env: ADAPTER=mongoid
    - gemfile: gemfiles/activerecord_5.gemfile
      env: ADAPTER=mongoid
    - gemfile: gemfiles/activerecord_6.gemfile
      env: ADAPTER=mongoid
    - gemfile: gemfiles/activerecord_6.gemfile
      rvm: 2.4.6
    - gemfile: gemfiles/activerecord_6.gemfile
      rvm: 2.3.8
    - gemfile: gemfiles/mongoid_5.gemfile
      env: ADAPTER=active_record
    - gemfile: gemfiles/mongoid_6.gemfile
      env: ADAPTER=active_record
    - gemfile: gemfiles/mongoid_7.gemfile
      env: ADAPTER=active_record
  allow_failures:
    - gemfile: gemfiles/mongoid_6.gemfile
    - gemfile: gemfiles/mongoid_7.gemfile

services: mongodb

addons:
  code_climate:
    repo_token: 6bd8d374b120a5449b9a4b7dfda40cc0609dbade48a1b6655f04a9bc8de3a3ee
